config/routes.rb
# typed: false
# frozen_string_literal: true

Rails.application.routes.draw do
  root "statics#about"

  resources :posts, only: %i[index show] do
    collection do
      get "list"
      get "all"
    end
  end

  get "about",     to: "statics#about"
  get "talks", to: "statics#talks"

  get "limuy", to: "statics#limuy"
  get "chloe", to: "statics#chloe"

  get "advent", to: "advent#index"
  post "advent/check_in", to: "advent#check_in"
  post "advent/reset_check_in", to: "advent#reset_check_in"
  post "advent/draw_voucher", to: "advent#draw_voucher"
  post "advent/redeem_voucher", to: "advent#redeem_voucher"
  post "advent/solve_puzzle", to: "advent#solve_puzzle"
  post "advent/message", to: "advent#message"
end

app/views/shared/_cursor_effect.html.slim
<script src="https://unpkg.com/cursor-effects@latest/dist/browser.js"></script>

javascript:
  window.addEventListener("load", (event) => {
    new cursoreffects.emojiCursor({ emoji: ["🙂"] });
  });

app/views/shared/_footer.html.slim
hr
.row
  .col-lg-8.col-md-10.mx-auto
    p.copyright.text-muted.text-center 
      = "Published on #{@post.created_at.strftime('%B %-d, %Y')}"
      
    ul.list-inline.text-center
      li.list-inline-item
        span.text-muted Find me at
      li.list-inline-item
        = link_to 'https://github.com/jenny-codes' do
          span.fa-stack.fa-lg
            i.fas.fa-circle.fa-stack-2x
            i.fab.fa-github.fa-stack-1x.fa-inverse style="padding: 1px 3px 0px 9px"
      li.list-inline-item
        = link_to 'https://www.linkedin.com/in/jenny-shih/' do
          span.fa-stack.fa-lg
            i.fas.fa-circle.fa-stack-2x
            i.fab.fa-linkedin.fa-stack-1x.fa-inverse style="padding: 1px 3px 0px 9px"
      li.list-inline-item
        = mail_to 'jinghua.shih@gmail.com' do 
          span.fa-stack.fa-lg
            i.fas.fa-circle.fa-stack-2x
            i.far.fa-envelope.fa-stack-1x.fa-inverse  style="padding: 1px 3px 0px 9px"
      li.list-inline-item
        = link_to 'https://medium.com/@jinghua.shih' do
          span.fa-stack.fa-lg
            i.fas.fa-circle.fa-stack-2x
            i.fab.fa-medium-m.fa-stack-1x.fa-inverse style="padding: 1px 3px 0px 9px"

app/views/shared/_google_analytics.html.slim
/Global site tag (gtag.js) - Google Analytics
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-134659049-1"></script>
javascript:
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-134659049-1');

app/views/shared/_navbar.html.slim
nav(class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav")
  .container
    a.navbar-brand href="/"  🌝
    button(class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation")
      span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      ul.navbar-nav.ml-auto
        li.nav-item
          = link_to "Posts", all_posts_path, class: "nav-link"
        li.nav-item
          a.nav-link href="/talks"  Talks
        li.nav-item
          a.nav-link href="/about"  About