config/routes.rb
# typed: false
# frozen_string_literal: true

Rails.application.routes.draw do
  root "statics#about"

  resources :posts, only: %i[index show] do
    collection do
      get "list"
      get "all"
    end
  end

  get "about",     to: "statics#about"
  get "talks", to: "statics#talks"

  get "limuy", to: "statics#limuy"
  get "chloe", to: "statics#chloe"

  get "advent", to: "advent#index"
  post "advent/check_in", to: "advent#check_in"
  post "advent/reset_check_in", to: "advent#reset_check_in"
  post "advent/draw_voucher", to: "advent#draw_voucher"
  post "advent/redeem_voucher", to: "advent#redeem_voucher"
  post "advent/solve_puzzle", to: "advent#solve_puzzle"
  post "advent/message", to: "advent#message"
end

app/controllers/posts_controller.rb
# typed: false
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate, except: %i[index all show]

  USERS = { ENV["admin_username"] => ENV["admin_password"] }.freeze
  POSTS_PER_PAGE = 10

  include Caching

  # Default view, now only when tag is clicked
  def index
    @posts_in_pages = cache("post_index", tag: params[:tag] || "none") do
      posts = PostArchive.list_published_order_by_id_desc(tag: params[:tag])

      posts.in_groups_of(POSTS_PER_PAGE, false)
    end

    @pagination = {
      curr_page: params[:page].try(:to_i) || 1,
      total_pages: @posts_in_pages.count
    }

    expires_in(10.minutes, public: true)
  end

  # Simplified view
  def all
    @posts = cache("post_all") do
      PostArchive.list_published_order_by_id_desc
    end

    expires_in(10.minutes, public: true)
  end

  # Internal view
  def list
    @posts = PostArchive.list_published_order_by_id_desc
    @draft = PostArchive.list_draft_order_by_id_desc
  end

  def show
    raise "need to support id field" if /^\d+$/.match?(params[:id])

    @post, @adjacent_posts = cache("post_show", id: params[:id]) do
      current_post = PostArchive.find_by_slug(params[:id])
      next_post    = PostArchive.next_of(current_post.id)
      prev_post    = PostArchive.prev_of(current_post.id)
      [current_post, { next: next_post, prev: prev_post }]
    end

    expires_in(10.minutes, public: true)
  end

  private

  def authenticate
    return unless Rails.env.production?

    authenticate_or_request_with_http_digest do |username|
      USERS[username]
    end
  end
end

app/views/posts/_posts_preview.html.slim
- posts.each do |post|
  .post-preview
    = link_to post_path(post.slug) do
      h2.post-title
        = post.title
      h3.post-subtitle
        = post.description
      p.post-meta
        - post.tags.each do |tag|
          = link_to "##{tag}", posts_path(tag: tag), class: "tag"
        br/
        = post.created_at.strftime('%B %-d, %Y')
  hr

app/views/posts/_tags_display.slim
.tags-container
  - tags.each do |tag|
    = link_to posts_path(tag: tag) do
      h2.tag ##{tag}

app/views/posts/all.html.slim
.row.mt-5
  .col-lg-8.col-md-10.mx-auto.my-5
    .list-group.list-group-flush
      - @posts.each do |post|
        = link_to post_path(post.slug), class: 'post-preview' do
          .list-group-item-action.flex-column.align-items-start.post-row
            h4.d-flex.w-100.justify-content-between
                = post.title

app/views/posts/index.html.slim
.row
  .col-lg-8.col-md-10.mx-auto.my-5.py-5
    = render 'posts/posts_preview', posts: @posts_in_pages[@pagination[:curr_page] - 1]

    /Pager
    .clearfix
      - if @pagination[:curr_page] > 1
        = link_to posts_path(page: @pagination[:curr_page] - 1), class: 'float-left' do
          i.fas.fa-chevron-left
          span.btn Previous
      - if @pagination[:curr_page] < @pagination[:total_pages]
        = link_to posts_path(page: @pagination[:curr_page] + 1), class: 'float-right' do
          span.btn Next
          i.fas.fa-chevron-right

app/views/posts/list.html.slim
.row
  .col-md-12
    .card
      .card-header.text-white.bg-primary
        h5 style='margin: 0;' PUBLISHED
      .card-body
        table.table
          thead
            tr
              th #
              th title
              th medium url
              th modified at
              th
          tbody
            - @posts.each do |post|
              tr
                td = post.id
                td = link_to post.title.truncate(15), post_path(post.id)
                td = link_to post.medium_url
                td = post.updated_at.strftime('%F')

  .col-md-12
    .card
      .card-header.text-white.bg-warning
        h5 style='margin: 0;' DRAFT
      .card-body
        table.table
          thead
            tr
              th #
              th title
              th modified at
              th
          tbody
            - @draft.each do |post|
              tr
                td = post.id
                td
                  = link_to post.title.truncate(50), post_path(post.id)
                td = post.updated_at.strftime('%F')

app/views/posts/new.html.slim
.container
  .row
    .col-md-12
      = form_with model: @post do |f|
        .form-row.justify-content-between
          .form-group.col-md-6
            = f.label :title
            = f.text_field :title, required: true, class: "form-control"
            / = f.text_field :tags,  class: "form-control"
          .form-group.col-md-4.align-right
            h4 references
            pre.pre-scrollable
              | h2.section-heading <br>
              | blockquote.blockquote <br>
              | img.img-fluid <br>
              | span.caption.text-muted <br>
        .form-group
          = f.label :description
          = f.text_area :description, class: "form-control"
        .form-group
          = f.label :body
          = f.text_area :body, 'data-provider': :summernote, required: true
        .form-group
          = submit_tag 'Hooray!', class: 'btn btn-warning', role: 'button'

app/views/posts/show.html.slim
- content_for :head do
  meta name="turbolinks-visit-control" content="reload"

/ Navigation
- content_for :container do
  = link_to post_path(@adjacent_posts[:next].slug), class: 'post-navigation post-nav-left' do
    i.fas.fa-chevron-left
    p.navigation-text = @adjacent_posts[:next].title.truncate(33)
  = link_to post_path(@adjacent_posts[:prev].slug), class: 'post-navigation post-nav-right' do
    i.fas.fa-chevron-right
    p.navigation-text = @adjacent_posts[:prev].title.truncate(33)

.row
  .col-lg-8.col-md-10.mx-auto.my-5.py-5.post-container
    .post-title
      h1 = @post.title
    = render 'tags_display', tags: @post.tags
    = @post.body.html_safe

= render '/shared/footer'